# Copyright © 2026 Mindclade, LLC. All Rights Reserved.
# Mindclade Proprietary and Confidential.
# SPDX-License-Identifier: LicenseRef-Mindclade-Proprietary

---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../templates/deny-holdout-mount.yaml
  - ../templates/deny-latest-tag.yaml
  - ../templates/deny-privileged.yaml
  - ../templates/partner-allowed-users.yaml
  - ../templates/require-image-policy.yaml
  - ../templates/require-resource-limits.yaml
  - ../templates/require-workload-identity.yaml
  - ../constraints/deny-holdout-bucket-mount.yaml
  - ../constraints/deny-latest-tag.yaml
  - ../constraints/deny-privileged.yaml
  - ../constraints/partner-namespace-isolation.yaml
  - ../constraints/require-image-policy.yaml
  - ../constraints/require-resource-limits.yaml
  - ../constraints/require-workload-identity.yaml
