# Copyright © 2026 Mindclade, LLC. All Rights Reserved.
# Mindclade Proprietary and Confidential.
# SPDX-License-Identifier: LicenseRef-Mindclade-Proprietary

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arc-artifact-authority
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  project: arc-artifact-authority
  source:
    repoURL: https://github.com/mindclade/gitops.git
    targetRevision: main
    path: arc
  destination:
    server: https://kubernetes.default.svc
    namespace: arc-systems
  syncPolicy:
    automated: {prune: false, selfHeal: true}
    syncOptions:
      - CreateNamespace=false
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
    retry:
      limit: 10
      backoff: {duration: 15s, factor: 2, maxDuration: 10m}
